title: Claes Adamsson
author:
  name: Claes Adamsson
  email: claes.adamsson@gmail.com
  avatar: "https://github.com/cladam.png"
  bio: >
    Sysadmin, developer, architect, and engineering leader turned DevOps advocate. 
    I’m passionate about sharing ideas and building tools that help teams deliver faster, better, and with clear business impact.
  location: Sweden
  linkedin_username: cadamsson
description: > 
  A personal site for projects, documentation, and thoughts on software development and delivery.

github_username: cladam

theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate

baseurl: ""
paginate: 5
paginate_path: "/page:num/"
permalink: pretty

collections:
  projects:
    output: true
