title: Claes Adamsson
author:
  name: Claes Adamsson
  email: claes.adamsson@gmail.com
description: > 
  A personal site for projects, documentation, and thoughts on software development.

github_username:  cladam

theme: minima
plugins:
  - jekyll-feed

baseurl: "/cldam.github.io"

collections:
  projects:
    output: true
